name: Trigger Test-1 Workflows

on:
  push:
    branches:
      - main # The branch to monitor for changes

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the trigger repo
        uses: actions/checkout@v3

    

      - name: Get the latest commit message in Prod-EN branch
        id: get_commit_en
        run: |
          latest_commit_message=$(git log -1 --pretty=%B origin/Prod-EN)
          echo "LATEST_COMMIT_EN=${latest_commit_message//\"/\\\"}" >> $GITHUB_ENV
          echo "LATEST_COMMIT_EN=${latest_commit_message}"  # For debugging purposes

      - name: Get the latest commit message in Prod-FR branch
        id: get_commit_fr
        run: |
          latest_commit_message=$(git log -1 --pretty=%B origin/Prod-FR)
          echo "LATEST_COMMIT_FR=${latest_commit_message//\"/\\\"}" >> $GITHUB_ENV
          echo "LATEST_COMMIT_FR=${latest_commit_message}"  # For debugging purposes

      - name: Trigger Prod-EN workflow in Test-1
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: Subhanshu0027/Test-1
          token: ${{ secrets.Repo_TOKEN }}
          event-type: trigger-prod-en
          client-payload: '{"commit_message": "${{ env.LATEST_COMMIT_EN }}"}'

      - name: Trigger Prod-FR workflow in Test-1
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: Subhanshu0027/Test-1
          token: ${{ secrets.Repo_TOKEN }}
          event-type: trigger-prod-fr
          client-payload: '{"commit_message": "${{ env.LATEST_COMMIT_FR }}"}'
