name: Trigger Test-1 Workflows

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the trigger repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Checkout the repository with Prod-EN and Prod-FR branches
        uses: actions/checkout@v3
        with:
          repository: Subhanshu0027/Test-1
          token: ${{ secrets.REPO_TOKEN }}
          path: other-repo
          ref: main

      - name: Fetch all branches from the other repo
        run: |
          cd other-repo
          git fetch --all

      - name: Checkout Prod-EN branch and get latest commit message
        id: get_commit_en
        run: |
          cd other-repo
          git checkout Prod-EN
          latest_commit_message=$(git log -1 --pretty=%B)
          echo "LATEST_COMMIT_EN=${latest_commit_message}" >> $GITHUB_ENV

      - name: Checkout Prod-FR branch and get latest commit message
        id: get_commit_fr
        run: |
          cd other-repo
          git checkout Prod-FR
          latest_commit_message=$(git log -1 --pretty=%B)
          echo "LATEST_COMMIT_FR=${latest_commit_message}" >> $GITHUB_ENV

      - name: Log the Prod-EN payload
        run: |
          echo "Triggering Prod-EN workflow in Test-1 with the following payload:"
          echo '{"event_type": "trigger-prod-en", "client_payload": {"commit_message": "${{ env.LATEST_COMMIT_EN }}"}}'

      - name: Trigger Prod-EN workflow in Test-1
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: Subhanshu0027/Test-1
          token: ${{ secrets.REPO_TOKEN }}
          event-type: trigger-prod-en
          client-payload: '{"commit_message": "${{ env.LATEST_COMMIT_EN }}"}'

      - name: Confirm Trigger for Prod-EN
        run: echo "Prod-EN trigger request sent. Check the repository dispatch logs for details."

      - name: Log the Prod-FR payload
        run: |
          echo "Triggering Prod-FR workflow in Test-1 with the following payload:"
          echo '{"event_type": "trigger-prod-fr", "client_payload": {"commit_message": "${{ env.LATEST_COMMIT_FR }}"}}'

      - name: Trigger Prod-FR workflow in Test-1
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: Subhanshu0027/Test-1
          token: ${{ secrets.REPO_TOKEN }}
          event-type: trigger-prod-fr
          client-payload: '{"commit_message": "${{ env.LATEST_COMMIT_FR }}"}'

      - name: Confirm Trigger for Prod-FR
        run: echo "Prod-FR trigger request sent. Check the repository dispatch logs for details."
