name: Trigger Test-1 Workflows

on:
  push:
    branches:
      - main # The branch to monitor for changes

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the trigger repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Checkout the repository with Prod-EN and Prod-FR branches
        uses: actions/checkout@v3
        with:
          repository: Subhanshu0027/Test-1/other-repo-name
          token: ${{ secrets.REPO_TOKEN }}
          path: other-repo
          ref: main

      - name: Fetch all branches from the other repo
        run: git fetch --all
        working-directory: other-repo

      - name: Get the latest commit message in Prod-EN branch
        id: get_commit_en
        run: |
          latest_commit_message=$(git log -1 --pretty=%B origin/Prod-EN)
          echo "LATEST_COMMIT_EN=${latest_commit_message}" >> $GITHUB_ENV
          echo "LATEST_COMMIT_EN=${latest_commit_message}"  # For debugging purposes
        working-directory: other-repo

      - name: Get the latest commit message in Prod-FR branch
        id: get_commit_fr
        run: |
          latest_commit_message=$(git log -1 --pretty=%B origin/Prod-FR)
          echo "LATEST_COMMIT_FR=${latest_commit_message}" >> $GITHUB_ENV
          echo "LATEST_COMMIT_FR=${latest_commit_message}"  # For debugging purposes
        working-directory: other-repo

      - name: Trigger Prod-EN workflow in Test-1
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: Subhanshu0027/Test-1
          token: ${{ secrets.REPO_TOKEN }}  # Ensure this is correct
          event-type: trigger-prod-en
          client-payload: '{"commit_message": "${{ env.LATEST_COMMIT_EN }}"}'

      - name: Trigger Prod-FR workflow in Test-1
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: Subhanshu0027/Test-1
          token: ${{ secrets.REPO_TOKEN }}  # Ensure this is correct
          event-type: trigger-prod-fr
          client-payload: '{"commit_message": "${{ env.LATEST_COMMIT_FR }}"}'
